name: Brothers4life
favicon: null
layout_spectrum: 0.9246032035443932
typography_spectrum: 0.49615062843076885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6500325419474393
  lightness: 0.07668538182042539
  saturation: 0.636578707722947
  rhythmicContrast: 0.3090039952658117
purpose: []
