name: B4L Brazilian Jiu Jitsu
favicon: null
layout_spectrum: 0.44898
typography_spectrum: 0.59849
title: B4L Brazilian Jiu Jitsu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2147'
    - '#ae172a'
    - '#f7f7f7'
    - '#e0a140'
    - '#847a92'
  brandStrength: 0.6875
  lightness: 0.25
  saturation: 0.636578707722947
  rhythmicContrast: 0.75
purpose: []
